services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - db_password
      - db_admin_password
      - db_root_password
    environment:
      DB_NAME: "${DB_NAME:-mariadb}"
      DB_USER: "${DB_USER:-user1}"
      DB_ADMIN: "${DB_ADMIN:-adm}"
      DB_PORT: "${DB_PORT}"
    restart: unless-stopped
    volumes:
      - vol-mariadb:/var/lib/mysql
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    secrets:
      - db_password
      - wp_user_password
      - wp_admin_password
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME:-localhost}"
      DB_NAME: "${DB_NAME:-harddrive}"
      DB_USER: "${DB_USER:-user1}"
      DB_HOST: "${DB_HOST:-mariadb}"
      WP_ADMIN_USER: "${WP_ADMIN_USER:-edugonza}"
      WP_ADMIN_PASSWORD: "${WP_ADMIN_PASSWORD:-1234}"
      WP_ADMIN_EMAIL: "${WP_ADMIN_EMAIL:-edugonza@42.fr}"
      WP_USER: "${WP_USER:-edu}"
      WP_USER_EMAIL: "${WP_USER_EMAIL:-edu@42.fr}"
      WP_USER_PASSWORD: "${WP_USER_PASSWORD:-1234}"
      WP_PORT: "${WP_PORT}"
      DB_PORT: "${DB_PORT}"
      NGINX_PORT: "${NGINX_PORT}"
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - vol-wordpress:/var/www/html
    networks:
      - inception
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        BONUS: "${BONUS}"
        DOMAIN_NAME: "${DOMAIN_NAME:-localhost}"
    restart: unless-stopped
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME:-localhost}"
      NGINX_PORT: "${NGINX_PORT}"
      WP_PORT: "${WP_PORT}"
      BONUS: "${BONUS}"
    ports:
      - "443:${NGINX_PORT}"
    depends_on:
      - wordpress
    volumes:
      - vol-wordpress:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_admin_password:
    file: ../secrets/db_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

volumes:
  vol-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/edugonza/data/mariadb
  vol-wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/edugonza/data/wordpress
