services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - db_password
      - db_admin_password
      - db_root_password
    environment:
      DB_NAME: "${DB_NAME:-mariadb}"
      DB_USER: "${DB_USER:-user1}"
      DB_ADMIN: "${DB_ADMIN:-adm}"
    restart: unless-stopped
    volumes:
      - vol-mariadb:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    secrets:
      - db_password
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME:-edugonza.42.fr}"
      DB_NAME: "${DB_NAME:-harddrive}"
      DB_USER: "${DB_USER:-user1}"
      DB_HOST: "${DB_HOST:-mariadb}"
      WP_ADMIN_USER: "${WP_ADMIN_USER:-edugonza}"
      WP_ADMIN_PASSWORD: "${WP_ADMIN_PASSWORD:-1234}"
      WP_ADMIN_EMAIL: "${WP_ADMIN_EMAIL:-edugonza@42.fr}"
      WP_USER: "${WP_USER:-edu}"
      WP_USER_EMAIL: "${WP_USER_EMAIL:-edu@42.fr}"
      WP_USER_PASSWORD: "${WP_USER_PASSWORD:-1234}"
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - vol-wordpress:/var/www/html
    networks:
      - inception
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DEBUG: "${DEBUG:-false}"
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - vol-wordpress:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_admin_password:
    file: ../secrets/db_admin_password.txt

volumes:
  vol-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gonzalo/code/educhigon/1.Learning/mariadb
  vol-wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gonzalo/code/educhigon/1.Learning/wordpress
# Change this for eval => /home/gonzalo/code/educhigon/1.Learning/ <=> /home/login/data/
# /home/${USER}/data/mariadb
# /home/${USER}/data/wordpress
