server {
	server_name server_one;
	listen 8080;
	host localhost;
	root ./data;
	index index.html;
	client_max_body_size 500k;
	error_page 400 ./data/error_pages/400.html;
	error_page 403 ./data/error_pages/403.html;
	error_page 404 ./data/error_pages/404.html;
	error_page 500 ./data/error_pages/500.html;

	location / {
		methods GET;
		autoindex off;
	}

	location /about {
		root ./data;
		index about.html;
		methods GET;
		autoindex off;
	}

	location /forbidden_folder {
		root ./data/forbidden_folder;
		allow none;
	}

	location /old_upload {
		return 301 /upload;
	}

	location /upload {
		root ./data/files;
		index files.html;
		methods GET;
		autoindex off;
	}

	location /upload-list {
		root ./data/files/upload;
		methods GET POST DELETE;
		autoindex on;
	}

	location ~ \.py$ {
		root ./data/cgi;
		cgi_path /usr/bin/python3;
		autoindex off;
		methods GET POST;
	}

	location /visitorbook {
		root ./data;
		index visitorbook.html;
		methods GET;
		autoindex off;
	}

	location /visitorbook/signing {
		root ./data/visitorbook;
		methods GET POST;
		autoindex off;
	}
}

server {
	server_name server_two;
	listen 8081;
	host localhost;
	root ./data/;
	index inexistent.html;
	client_max_body_size 500k;
	error_page 400 ./data/error_pages/400.html;
	error_page 403 ./data/error_pages/403.html;
	error_page 404 ./data/error_pages/404.html;
	error_page 500 ./data/error_pages/500.html;

	location / {
		methods GET;
		autoindex on;
	}

	location /about {
		root ./data;
		index about.html;
		methods GET;
		autoindex off;
	}

	location /forbidden_folder {
		root ./data/forbidden_folder;
		allow none;
	}

	location /upload {
		root ./data/files/;
		index files.html;
		methods GET;
		autoindex off;

	}

	location /upload-list {
		root ./data/files/upload;
		methods GET POST DELETE;
		autoindex on;
	}

	location ~ \.py$ {
		root ./data/cgi;
		cgi_path /usr/bin/python3;
		autoindex off;
		methods GET POST;
	}

	location /visitorbook {
		root ./data;
		index visitorbook.html;
		methods GET;
		autoindex off;
	}

	location /visitorbook/signing {
		root ./data/visitorbook;
		methods GET POST;
		autoindex off;
	}
}
